cc_library(
    name = "neptune_headers",
    hdrs = [
        "face_detector.h",
        "types.h",
        # add other header files here
    ],
    visibility = ["//visibility:public"],
    strip_include_prefix = "//core/include",
)